feat: add docker compose
rgutierreza1994/LoungeRent pull request #1
Opened 2023-08-23 14:21 UTC by Figaarillo

2023-08-23 14:47 UTC, rgutierreza1994 requested changes
algunos cambios deben hacerse

2023-08-23 14:47 UTC, rgutierreza1994 commented on back/docker-compose.yml
> +  db-lounge-rent:
porfa agrega el usuario de servivio
DB_USERNAME=user

2023-08-23 14:47 UTC, rgutierreza1994 commented on back/docker-compose.yml
> +    image: mysql:latest
usa una version estable de mysql

2023-08-23 14:47 UTC, rgutierreza1994 commented on back/docker-compose.yml
> +      MYSQL_DATABASE: lounge_rent
agrega el volumen de inicializacion como :

    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
con el archivo con este contenido
`GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';`

2023-08-23 23:08 UTC, Figaarillo commented on back/docker-compose.yml
> +    image: mysql:latest
Elegí `MySql 5.7` como versión estable.

2023-08-24 11:52 UTC, rgutierreza1994 approved these changes
lgtm

2023-08-24 11:52 UTC, merged